### ISSUE TITLE
capture.output with `type=` parameter

### ISSUE THREAD

**Issue by jimhester** [r-lib/backports#15]
A `type` parameter was added to `capture.output()` for R 3.2.1-patched which passes `type` and `split` down to the internal `sink()` call. https://github.com/wch/r-source/commit/d00b404783dd261f1598157b87d042d9e91c25f5.

It would be handy to add a backport so `capture.output(type = "message")` could be used on e.g. R 3.1.

**Comment by mllg** [comment]
Implemented in 9d1455913de8d7f271a9e6fd1d81b0963e71d0c0.

I opted to backport this for R < 3.3.0 though. Binaries are only build for the minor versions, not for every patchlevel. Therefore it is rather difficult to reliably predict what happens if you use R-3.2.1 but using binaries build with R-3.2.3. Let me know if you encounter any problems.
